### ISSUE TITLE
runParity(): Exitcode 1, with signal null

### ISSUE THREAD

**Issue by Kalibar** [paritytech/js-libs#212]
using parity electron.
`runParity({
		flags: ['--chain kovan --light --ws-origins all'],
		onParityError: (err) => {
		  console.log(err)
		}
	});`

`Error: Exit code 1, with signal null.
    at ChildProcess.<anonymous> (/.../node_modules/@parity/electron/lib/runParity.js:153:43)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
`

**Comment by axelchalon** [comment]
Can you manually run `parity --chain kovan --light --ws-origins all` without problem on the parity binary returned by `getParityPath()` ?

**Comment by Kalibar** [comment]
@axelchalon yes, running parity directly from console works as expected

**Comment by Kalibar** [comment]
all right..
this does work
`["--chain", "kovan", "--light", "--ws-origins", "all"]`
this does not 
`["--chain", "kovan", "--light", "--ws-origins all"]`
`['--chain kovan --light --ws-origins all']`
cheers ;)
